language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: NJqPcyyIkfTp0hS+RKaJEG5/Mm5Px2MFnlScsw7jZ5b0DC6DDekM4APjJ+1qXcvxj/0dbfMiL/nmW424HEN+u0Tu+oVsRnviVgGjZyNurmg40uJa/5dfp6XYGN7IBMoQS96KEoYYqhdd33Vxghx/49VCB6NcThkYbJuTK7nX34WVxectcxb2uBCShBV96IBumQlF8Y5AqKxHapkRFvKFG2TDFu0LGxStJMe6kMfKSYtaEPpH+7j2yLY0BeRStv+dJbB0hfYmb2FE9Tn1pN2dnqqBuWQ41WT/P/aUcqPR/Q9TOJVObMIvjg4VHUqfR0AshaipgjKlOzREaTSW8XdwQ+3J01w2qvAwt8V/xSH3CyVtDJwm89ZpiWyA3cBOAdy1fL52DxACffORBHTDIR9nixZl51oPkGimCJ6vk8yOmPd8rvEHXrmMF6K7j8FM0aXw/ZxoBG4fjltHkZ0xt+LzeIwPBAVEYp+oxb/6t149ocKY1ASasS3haXEwTf/543BiwDsxyPbOHF0Qg896wr4HNTPyBawFyrh+4E8mwyLD4GEWR0B339XBtEliZTspT+U6g3eRIbg+rlu8cGAQ2mOWYBErEJZVFvfK96r+a9JKjGFQhCGqvlunljQiWT6Ph2bqWi4GWASt+nLjOUGxq+RAYH4fQbmFqh8T4ezrRQa37XY=
  app: cursodevops-pipeline
  edge: true
