language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: J2Rcu1y8qXIonjxDu6faIpk26iWkQGrXLvLwRtmcALDTAYv/WudQfkdMqyXisMHgT+5LJ+jTdOhRrGFic36KSz5Zt3JlWlKEtKsRNXmZIHj3txwY8pzfebYlICDJS+/Y4BwHY/w5cjArGjSafsuOYdP86fs2Jxd5LCdYBlT+6wg5yO59Gst/mPgl8ZASLBKm0qg2mve0dE42RxOu9cwEjL3vul+q6+bkZBhmL/4s4gOZxhCqNf7DLokY4Waej2Fc7yeqliTY3VhTbYWSbIqyCHs7Q7yLrlqUq1GTJwdueLPbXrjrjcJFRphmQchL1FMML0ovbCX74aYFplkOcUWDq0IKVmH00PTXf4tlVTOf7I6Puqutzlzh2gOWzYK5eYlQRn7WvPUp27xKkwgdeT24Jjd0lZa9T3t6gMOBUls8Z5eS1bzKo9fqW+GRSg4Jd7bZx2bZjoJlnrEVcUxb6LdAUStN87pFCAZ8wMhTtzIrCYI6f/z81q5RMheVznTtjq71KkhM+ZjAFfwJH/T/CXYGOdIcZNtrMyxNXCIP2GUiodDa6kDMzmiiQr4yknbsKgObR8AeKrkHVgEmRLsk+L1/bVMi1CZe8+rHzoXcfa3FlA8t5ttEZwvOwSEBcxHvFyqkFzlbxHII/Nwe6Z+9Vnv+YzvCLFob17qd/ydXXFKnwnM=
  app: cursodevops-pipeline
  edge: true
