language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: Tw2/tegJmqsxMxnku0nmAnOuKbr8nXXluT015jjrG7B/qZ3U1eh1sa1Z52egzVhF/CkFF73aZGfzrk0EyjS6Ajp31tQ5sbQpWv9YX27OPoepkz2/2qlTUrWYprnw46NjC4iC0K2YVMDWP/3iNrjVVRn2Cem7lx0CEkNQIKXJWIv79jQBvIqVbu9oLl+3F2DBNfDT8uGvTw9qYE+V0QY/OSF+WB7IOQNfO3hHSZqvtxIF/D40k5rAuvcEsyZFVSPPEt76r7SySAS+oy9I8PSCumHUCRmTP8VNMfd1vcZpI9UdMoTI+80gE4grP1rjs7A3wDH3wlh8Rba5flGp4FSZ3iAJb3QhCXM6cduNJnLGSfbFLHWE6TDmmQrMG8bafOtQezgWMNQTLlhU8o4VRFUQo2zIdmY5f4lLEgPHA7a0x9KpD2cvUq5SykHDjnQkCZLGMHUVtIOd9FjjtQuo1YOiQuAsaKINjReG+NZETCcqf/4f6cgpcs3RPyAG8dld7JYMBbAns3xwhygyhlCqKEbUkpG+Ab1wQ1s7P+b/1H5T1WcM4YNhVWNrhS02DTo0Eqel4fEZF+ByF679gbw0zyMDdiSByzhTZlrSmaEJHMioGZuml+szsXNSfps1D5bLwR48QRD3iIzWokj53tvM++iKYYacpMEy1Ccc83MobesYJmA=
  app: cursodevops-pipeline
  edge: true
